site_name:    Developer Docs
repo_url:     https://github.com/YenHub/developer-docs
repo_name:    YenHub/developer-docs

theme:
  name:       material
  favicon:    img/favicon.ico
  logo:       img/logo.png
  icon:
    repo:     fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.sections
  palette:
    primary:  light-blue

extra:
  social:
    - icon:   fontawesome/brands/linkedin
      link:   https://www.linkedin.com/in/iangilkes
      name:   Find me on LinkedIn

extra_css:
  - stylesheets/extra.css

nav:
    - Home:   index.md

    - 'Software Engineering':
        - JavaScript:
            - 'Snippets & Tools':
                - 'SVG Word Wrap Hack': 'engineering/javascript/snippets/svg-wrap-hack.md'
            - NPM:
                - 'Working with local packages': 'engineering/javascript/npm/local-packages.md'
        - GIT:
            - 'Git QuickStart Cheat Guide': 'engineering/git/git-quickstart.md'
            - 'Git Friend Finder!': 'engineering/git/friend-finder.md'
            - 'Migrating a Repo': 'engineering/git/migrate.md'
            - 'Rebase -vs- Merge': 'engineering/git/rebase-merge.md'
        - Misc:
            - 'Atom Editor: Backup Process': 'engineering/misc/atom.md'
            - 'The Joel Test': 'engineering/misc/joel.md'

    - DevOps:
        - 'Linux Tips':
            - 'General Tips': 'devops/linux-tips/general-tips.md'
            - 'User Management': 'devops/linux-tips/user-management.md'
            - "Let's Encrypt": 'devops/linux-tips/lets-encrypt.md'
            - 'TomCat QuickStart': 'devops/linux-tips/tomcat.md'

        - 'Databases':
            - MySQL:
                - 'MySQL Bash Backup Script': 'devops/databases/bash-mysql-backup.md'
            - PostgreSQL:
                - 'PostgreSQL Quick Start': 'devops/databases/postgres.md'

        - 'Misc':
            - 'Virtual Box HD Management': 'devops/misc/vbox.md'
            - 'Redis Quick Start': 'devops/misc/redis.md'
            - 'Docker Quick Start': 'devops/misc/docker.md'

    - SysAdmin:
        - Windows:
            - 'Vmmem High Memory Usage': 'sysadmin/windows/vmmem.md'