site_name:    Developer Docs

theme:
  name:       material
  favicon:    img/favicon.ico
  logo:       img/logo.png
  icon:
    repo:     fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
  palette:
    primary:  light-blue

extra:
  social:
    - icon:   fontawesome/brands/linkedin
      link:   https://www.linkedin.com/in/iangilkes
      name:   Find me on LinkedIn
  generator:  false

repo_url:     https://github.com/YenHub/developer-docs
repo_name:    YenHub/developer-docs

nav:
    - Home:   index.md
    - 'Linux Tips':
        - 'General Tips': 'linux-tips/general-tips.md'
        - 'User Management': 'linux-tips/user-management.md'
    - 'Misc':
        - 'Atom Editor: Backup Process': 'misc/atom.md'