site_name:    Developer Docs

theme:
  name:       material
  favicon:    img/favicon.ico
  logo:       img/logo.png
  icon:
    repo:     fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
  palette:
    primary:  light-blue

extra:
  social:
    - icon:   fontawesome/brands/linkedin
      link:   https://www.linkedin.com/in/iangilkes
      name:   Find me on LinkedIn

repo_url:     https://github.com/YenHub/developer-docs
repo_name:    YenHub/developer-docs

nav:
    - Home:   index.md
    - 'Linux Tips':
        - 'General Tips': 'linux-tips/general-tips.md'
        - 'User Management': 'linux-tips/user-management.md'
        - 'MySQL Bash Backup Script': 'linux-tips/bash-mysql-backup.md'
    - JavaScript:
        - 'Snippets & Tools':
            - 'SVG Word Wrap Hack': 'javascript/snippets/svg-wrap-hack.md'
        - npm:
            - 'Working with local packages': 'javascript/npm/local-packages.md'
    - 'Misc':
        - 'Atom Editor: Backup Process': 'misc/atom.md'
        - 'Virtual Box HD Management': 'misc/vbox.md'
        - 'The Joel Test': 'misc/joel.md'

extra_css:
  - stylesheets/extra.css