name:                      🚀 Deploy Docs on push
on:                        push
  push:
    branches:
      - master
    paths:
      - 'site/**'
jobs:
  web-deploy:
    name:                  🎉 Deploy
    runs-on:               ubuntu-latest
    steps:
    - name:                🚚 Get latest code
      uses:                actions/checkout@v2.3.2

    - name:                🔨 Build Docs
      uses:                actions/setup-python@v2
        with:
          python-version:  3.x
      run:                 pip install mkdocs-material
      run:                 mkdocs gh-deploy --force

    - name:                🔥 Sync files to the server
      uses:                SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server:            ${{ secrets.ftpserver }}
        username:          ${{ secrets.ftpuser }}
        password:          ${{ secrets.ftppass }}
        local-dir:         ./site/
        server-dir:        public_html/